console.log("hi")

// This is a placeholder taken from https://gist.githubusercontent.com/ajzeigert/32461d73c17cfd8fd475c0049db451f5/raw/51b7af34b5ad50207dc9b59b583f14fa20b2e446/tarot.json; replace
const full_tarot = [
	{"name":"The Fool",
	"description":"The Fool is our hero. They hold the willingness to start something new and to take risks.",
	"interpretation":"Standing aloft, feeling the pull of a new beginning, you're ready to take a risk and step into the unknown. Who are your loyal companions? What do you need to take with you as you abandon the old and start the new?","suite":"major","img":"img/0%20-%20The Fool.png"},
	{"name":"The Magician","description":"The Magician stands in their power. They know they can manifest anything they desire.","interpretation":"Whatever you want you can manifest. What are your natural resources%20-%20what comes easily to you? How do you want to use the gifts you’ve been given? Check in with your emotions, passions, communication and manifesting skills to make it so!","suite":"major","img":"img/1%20-%20The Magician.png"},
	{"name":"The High Priestess","description":"The divine feminine, gateway to the secrets of the web of life. The High Priestess holds wisdom and possibility.","interpretation":"Open yourself to creativity and flow. Allow the divine feminine to be experienced and not sought. Feel it tingle in your fingertips and energise your creativity. Be at one with the fullness of your potential, without knowing where it will go. Trust and enjoy.","suite":"major","img":"img/2%20-%20The High Priestess.png"},
	{"name":"The Empress","description":"The Empress is the fertile ground of a new project, or the nurturing 'good mother'. She is nourishing, nature, soul purpose.","interpretation":"Allow yourself or this new creative idea to unfold in its natural time. Resist the need to push to make it happen. You are in a good, fertile place for nurturing newness and for being in flow.","suite":"major","img":"img/3%20-%20The Empress.png"},{"name":"The Emperor","description":"The Emperor stands strong. He is the embodied masculine, the archetypal father-figure. Organised and boundaried.","interpretation":"It’s time to make plans. Get thinking around practical next steps. Who is with you on this path? Who’s not on the same page as you? Where can you practice your healthy boundaries?","suite":"major","img":"img/4%20-%20The Emperor.png"},{"name":"The Hierophant","description":"The Hierophant holds sacred wisdom. He is a masculine spiritual teacher and gatekeeper to higher knowledge.","interpretation":"Where are you in your spiritual journey? What important lessons have been learned that are now ready to be applied in your life? ","suite":"major","img":"img/5%20-%20The Hierophant.png"},
	{"name":"The Lovers","description":"Love, lovers, choice from the heart… The Lovers card is self-love, and soul-mate, love, compassion, sensuality and sexuality.","interpretation":"This card shows the Lovers together, but separate, both dancing to their own song, side by side. Is this about a person? Or is it about love, compassion and self-love. How can you make this choice from the heart, and not fear? Where can you dance under the moon on the feathery flames of love?","suite":"major","img":"img/6%20-%20The Lovers.png"},{"name":"The Chariot","description":"It's time to take action when the Chariot appears, there is an ambitious forwards motion, self-confidence and certainty.","interpretation":"Which area of your life feels like it needs action, ambition and expansion? Trust that you have the power to make this choice, and that it's the struggles that make you stronger. It's time to 'go for it'.","suite":"major","img":"img/7%20-%20The Chariot.png"},
	{"name":"Strength","description":"Strength is the card of mastery through self-awareness. It is also physical strength and courage.","interpretation":"Let the fire of self-awareness and inner strength burn bright in your heart and belly. Paint the sky with your vision! Don’t be afraid to take the steps that your intuition whispers to you.. these are the steps will lead you closer to your self-love and freedom. Include the gentle voice of intuition to feel empowered and strong.","suite":"major","img":"img/8%20-%20Strength.png"},{"name":"The Hermit","description":"The Hermit spends time in contemplation, withdrawing and taking time out for meditation and self-reflection.","interpretation":"What makes your heart sing? What comes easily to you? These may be some of the contemplations required right now.  This card suggests it's time to look within, to breathe and reflect on next steps before taking action. Don’t rush.","suite":"major","img":"img/9%20-%20The Hermit.png"},
	{"name":"Wheel of Fortune",
		"description":"Wheel of Fortune is the destiny card. Some things are out of our hands, including the turning of time and the inevitability of change.",
		"interpretation":"Do you feel as though the Wheel of Fortune is turning in your favour? Are you ready for change? This card reminds us of the cycle of change and that sometimes things just feel like destiny. Enjoy the good times and don't sweat the bad stuff as: 'this too shall pass'. ","suite":"major","img":"img/10%20-%20Wheel of Fortune.png"},
	{"name":"Justice","description":"Balance. Contracts. Fairness. Ethical codes explored. Justice reminds us to connect to the contract with ourselves and others. ",
		"interpretation":"Do you feel this path is unfair? Is there a contract that needs a second look? Or perhaps an inner reflection on your moral standpoint? Take a moment to breathe, pause and reflect on where you feel BALANCE. This card will get you there.","suite":"major","img":"img/11%20-%20Justice.png"},
	{"name":"The Hanged Man","description":"The Hanged Man has sacrificed himself, but in doing so he's gained a new perspective and so encourages us to let go.","interpretation":"There is no escaping this current situation, other than to allow it to pass and to learn and heal from it. Stop repeating the same struggle. Breathe and let go. Find the new perspective that you need.","suite":"major","img":"img/12%20-%20The Hanged Man.png"},
	{"name":"Death","description":"Death. From endings there come new beginnings. This is a necessary period of change.","interpretation":"In order to make way for the new, something must be released. This feels scary because an ending can cause feelings of grief and loss. However, do not be afraid, this is a necessary step to make way for the new. You may not know what is in store until you have the courage to accept this ending.","suite":"major","img":"img/13%20-%20Death.png"},
	{"name":"Temperance","description":"A consistent 'tempering', checking in with one-self, creates balance and harmony. Temperance speaks to the capacity to work with both the 'light' and the 'dark' in order to stay balanced. Divine timing.","interpretation":"You're feeling in balance right now. This is because you see both sides of the picture and accept both sides of the story. It's ok to hold both at the same time as this duality is everywhere in nature. Trust in the divine timing of things.","suite":"major","img":"img/14%20-%20Temperance.png"},{"name":"The Devil","description":"Sometimes it's \"better the devil you know\", but this is where you can get stuck. The Devil confronts us with our shadow side and tells us not to let fear get in the way.","interpretation":"Where the devil are you feeling stuck? Which part of you is desiring more and more? What are you afraid of? This card is an invitation to get to know yourself, your characteristics and habits, so you can discover new, and more healthy, ways of being.","suite":"major","img":"img/15%20-%20The Devil.png"},{"name":"The Tower","description":"The Tower that needs to come down. Outdated survival strategies that no longer serve you are being challenged. You’re feeling rocked to the core, but this change is good for you.","interpretation":"The Tower may look strong but it’s made from flimsy paper and needs to be burned. Outdated patterns of behaviour that no longer serve you are ready to be sent skyward. You might not feel ready but life is pushing you to make this change – and it’s a change for the better. Let go and feel the feels. Get ready with your lighter%20-%20this paper tower needs to go up in flames.","suite":"major","img":"img/16%20-%20The Tower.png"},{"name":"The Star","description":"The guiding star and healing light. The Star is your muse, your  inspiration. When the Star shows up in a reading the healing has occurred, and you are creatively at one with your muse.","interpretation":"You are held, you are healing.. Stay focussed on following what lights you up, connect to your muse, your creativity. Take time to be gentle with yourself. You've got this.","suite":"major","img":"img/17%20-%20The Star.png"},{"name":"The Moon","description":"As the Moon moves through its 28 day cycle our earthly experience waxes and wanes, ebbs and flows. Trust in the cycle of life. Trust in your instincts. Trust that where there is darkness there must also be light.","interpretation":"Where is the moon cycle currently? What is your instinct telling you? There may be a part of your unconscious that is ready to be seen in the light, to be discovered, tended to and included. Don't be afraid of the parts of you hidden in darkness. Gently bring them into the light.","suite":"major","img":"img/18%20-%20The Moon.png"},
	{"name":"The Sun","description":"The Sun is a big fat YES! It is beauty, it is radiance. Be in your brightness, your rebirth, your resurrection. Sometimes this card means birth or baby.","interpretation":"Where is your 'Yes'? What small step can you take towards it? Can you give yourself permission to be in your brightness? Feel your way into your YEAH BABY!","suite":"major","img":"img/19%20-%20The Sun.png"},{"name":"Judgement","description":"When the Judgement card shows this means you've put in the work and you're ready for the new. It's time for evaluation and to follow your calling. ","interpretation":"This is a new beginning and you are ready for it. Relax, evaluate, follow your intuition. Use your self-awareness from the lessons you've learned to move into the new. It's time.","suite":"major","img":"img/20%20-%20Judgement.png"},
	{"name":"The World","description":"The World card is completion, wholeness, arrival. You are exactly where you are supposed to be.","interpretation":"Take your time to revel in how far you've come. If you don't feel ready yet you are almost there. Success is guaranteed. Take it slow. You are ready.","suite":"major","img":"img/21%20-%20The%20Universe.png"}];

const phases = ["The starting point",
	"Next steps",
	"Hurdle",
	"What to 'call in'",
	"Potential outcome"];

/**
 * Shuffles array in place. ES6 version
 * @param {Array} a items An array containing the items.
 */
 function shuffle(a) {
    for (let i = a.length-1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

function deal(tarot,do_shuffle) {
	if(do_shuffle) {shuffle(tarot);}
	console.log(JSON.stringify(tarot[0]))
	console.log("...");
	//const phases = [1,2,3,4,5];
	for(const i of phases.keys()) {
		const pn = `phase_${i}`;
		const div_phase = document.getElementById(pn);
		//div_phase.innerHTML = `${tarot[i].description}<br><img src="${tarot[i].image}">`;
		const in_context = tarot[i].interpretation;
		div_phase.innerHTML = `<img style="width:50%" src="${tarot[i].img}"><p><b>General:</b> ${tarot[i].description}<p><b>Description:</b> ${in_context}<br>`;
		const h2_phase = document.getElementById(`ph_${i}`);
		h2_phase.innerHTML = `${phases[i]}: ${tarot[i].name}`
	};

}